### ISSUE TITLE
output some useful data?

### ISSUE THREAD

**Issue by joelgombin** [juba/scatterD3#24]
I have no idea at all whether this is doable, but it would be absolutely great to be able to output some data once the exploration of the scatterplot is finished. I'm thinking in particular to the positions of the labels (updated when one drags them): that's be very helpful to generate a dataframe that could then be used, e.g., to make a `ggplot2` scatterplot with the adequate positions for the labels...

**Comment by juba** [comment]
This could be quite useful, but I see at least two difficulties...

As far as I know, `htmlwidgets` allows to pass data and arguments from R to JavaScript, but it's a one-way communication : there is no way to send data back to R. So it seems that the only ways would be either to print things in console (ok for some things, but not suitable for large output) or maybe to save to a file (but I'm not entirely sure if it's possible from JavaScript code).

The second point is the way to trigger this output. it's quite easy to add a control if the widget is in a shiny app, but otherwise it should be either a keystroke (if doable) or a specific button somewhere.

So, a good idea, but the implementation needs a bit of thinking...

**Comment by joelgombin** [comment]
That's tricky indeed... I guess that could be done in a shiny app (see https://github.com/ramnathv/htmlwidgets/issues/86#issuecomment-164095079), what do you think? Do you think it would be worth the effort?

**Comment by juba** [comment]
Outputting code to console or inserting it in a script is quite easy in a shiny app/gadget, but here we have to get data directly from JavaScript, and export it in a usable way. It could be added as a shiny button with a callback function which would, for example, offer to save labels position to a CSV file (well, at least I guess it should be possible).

It would be even better to put a control on the plot itself, in the same way `ggvis` does it, for example. A symbol which would appear on hover and, when clicked, offer to reset zoom / export SVG / launch lasso selection / export labels position. Bonus point : it would add these features to plots outside of shiny apps.

The problem is that I'm not sure I will have enough time to look at this in the following weeks... but I think it would definitely be useful.

**Comment by juba** [comment]
Labels positions export should now be possible. The new "gear menu" allows to export them to a CSV file for later reuse. There's a [quick example](https://rawgit.com/juba/scatterD3/master/vignettes%2Fintroduction.html#custom-labels-positions-export) in the introduction vignette.

Feel free to reopen the issue if needed.

**Comment by timelyportfolio** [comment]
Not impossible but certainly not trivial.  I'll save this as a challenge for some other day.
