### ISSUE TITLE
Pass the index of the clicked point back to Shiny

### ISSUE THREAD

**Issue by GiuseppeDiGuglielmo** [juba/scatterD3#50]
I am not able to pass the index of a clicked point back to Shiny.

I am trying the suggested:

```
scatterD3(data = mtcars, x = wt, y = mpg,
  click_callback = "function(id, index) {
  if(id && typeof(Shiny) != 'undefined') {
      Shiny.onInputChange('selected_point', index);
  }
}")
```

And I am trying to place
`verbatimTextOutput(paste("Index of clicked point : ", input$selected_point))`
in the UI, but without success.

Is it possible to have a working example in the Sample?  
https://data.nozav.org/app/scatterD3/

**Comment by juba** [comment]
Hi,

The problem is that you have to add your `verbatimTextOutput` in your `ui` definition, but the `input$selected_point` should go in your `server` part. I just added a more complete example in the visual guide :

https://rawgit.com/juba/scatterD3/master/vignettes/introduction.html#javascript-callback-on-clicking-point

Hope this helps.
